# This values.yaml file creates the resources for a P/D disaggregation scenario
# Uses a small model: facebook/opt-125m
# See also defaults in chart values.yaml

# When true, LeaderWorkerSet is used instead of Deployment
multinode: false

modelArtifacts:
# This is the model name used to start vLLM.
  name: ibm-ai-platform/micro-g3.3-8b-instruct-1b
  labels:
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: micro-g3.3-8b-instruct-1b
  uri: hf://"{{ .Values.modelArtifacts.name }}"
  size: 20Gi

# Describe routing requirements. In addition to service level routing (OpenAI model name, service port)
# also describes elements for Gateway API Inference Extension configuration
routing:
  servicePort: 8000

  # other fields are inherited from chart values.yaml
  proxy:
    secure: false

# Decode pod configuation
decode:
  create: true
  replicas: 1
  containers:
  - name: "vllm-spyre"
    image: "ghcr.io/llm-d/llm-d:v0.2.0"
    modelCommand: vllmServe
    args:
      - "--enforce-eager"
      - "--kv-transfer-config"
      - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
    env:
      - name: CUDA_VISIBLE_DEVICES
        value: "0"
      - name: UCX_TLS
        value: "cuda_ipc,cuda_copy,tcp"
      - name: VLLM_NIXL_SIDE_CHANNEL_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: VLLM_NIXL_SIDE_CHANNEL_PORT
        value: "5557"
      - name: VLLM_LOGGING_LEVEL
        value: DEBUG
    ports:
      - containerPort: 8200  # from routing.proxy.targetPort
        protocol: TCP
      - containerPort: 5557  # NIXL side channel
        protocol: TCP
    resources:
      limits:
        memory: 16Gi
        cpu: "16"
      requests:
        cpu: "2"
        memory: 4Gi
    mountModelVolume: true

# Prefill pod configuation
prefill:
  create: true
  replicas: 1
  containers:
  - name: "vllm-spyre"
    image: "ghcr.io/llm-d/llm-d:v0.2.0"
    modelCommand: vllmServe
    args:
      - "--enforce-eager"
      - "--kv-transfer-config"
      - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
    env:
      - name: CUDA_VISIBLE_DEVICES
        value: "0"
      - name: UCX_TLS
        value: "cuda_ipc,cuda_copy,tcp"
      - name: VLLM_NIXL_SIDE_CHANNEL_PORT
        value: "5557"
      - name: VLLM_NIXL_SIDE_CHANNEL_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: VLLM_LOGGING_LEVEL
        value: DEBUG
    ports:
      - containerPort: 8000  # from routing.servicePort
        protocol: TCP
      - containerPort: 5557  # NIXL side channel
        protocol: TCP
    resources:
      limits:
        memory: 16Gi
        cpu: "16"
      requests:
        cpu: "2"
        memory: 4Gi
    mountModelVolume: true
