# This values.yaml file creates the resources for a P/D disaggregation scenario
# Uses a small model: facebook/opt-125m
# See also defaults in chart values.yaml

# When true, LeaderWorkerSet is used instead of Deployment
multinode: false

modelArtifacts:
# This is the model name used to start vLLM.
  name: vllm-micro-granite
  labels:
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: vllm-micro-granite
  uri: hf://"{{ .Values.modelArtifacts.name }}"
  size: 20Gi

# Describe routing requirements. In addition to service level routing (OpenAI model name, service port)
# also describes elements for Gateway API Inference Extension configuration
routing:
  proxy:
    enabled: false  # removes sidecar from deployment - no PD in inference scheduling
    targetPort: 8000  # controls vLLM port to matchup with sidecar if deployed

  # other fields are inherited from chart values.yaml
  proxy:
    secure: false

# Decode pod configuation
decode:
  create: true
  replicas: 2
  containers:
  - name: "vllm-spyre"
    image: "quay.io/satyam16/llm-d-spyre-dev:v0.1.23"
    command:
      - /bin/bash
      - -c
      - |
        cd /tmp && \
        mkdir -p export_dtcompiler && \
        chmod 777 export_dtcompiler && \
        source /etc/profile.d/ibm-aiu-setup.sh && \
        exec python3 -m vllm.entrypoints.openai.api_server "$@"
      - --
    args:
        - --model=/mnt/models
        - --port=8000
        - --served-model-name={{.Name}}
        - --max-model-len=3072
        - --max-num-seqs=16
        - --enable-prefix-caching
        - --enable-chunked-prefill
        - --trust-remote-code
        - --prefix-caching-hash-algo sha256_cbor
        - --kv-events-config "{\"enable_kv_cache_events\":true,\"publisher\":\"zmq\",\"endpoint\":\"tcp://vllm-stack-kv-cache-manager.llm-d-spyre.svc.cluster.local:5557\",\"topic\":\"kv@${POD_IP}@ibm-ai-platform/micro-g3.3-8b-instruct-1b\"}"
        - "--model"
        - "ibm-ai-platform/micro-g3.3-8b-instruct-1b"
    env:
        - name: FLEX_DEVICE
          value: VF
        - name: TOKENIZERS_PARALLELISM
          value: "false"
        - name: DTLOG_LEVEL
          value: error
        - name: TORCH_SENDNN_LOG
          value: CRITICAL
        - name: VLLM_SPYRE_USE_CB
          value: "1"
        - name: VLLM_SPYRE_REQUIRE_PRECOMPILED_DECODERS
          value: "0"
        - name: TORCH_SENDNN_CACHE_ENABLE
          value: "0"
        - name: VLLM_SPYRE_USE_CHUNKED_PREFILL
          value: "1"
        - name: TMPDIR
          value: /tmp
        - name: HOME
          value: /tmp


    ports:
        - containerPort: 8000
          name: vllm
          protocol: TCP

    resources:
      limits:
        memory: 40Gi
        cpu: "10"
      requests:
        cpu: "2"
        memory: 4Gi
    mountModelVolume: true

# Prefill pod configuation
prefill:
  create: false
